version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    open-pull-requests-limit: 6
    schedule:
      interval: monthly
    assignees:
      - clarkedb

    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: next
        update-types: ['version-update:semver-major']
      - dependency-name: react
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react'
        update-types: ['version-update:semver-major']
      - dependency-name: react-dom
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react-dom'
        update-types: ['version-update:semver-major']
